# Generated by Django 3.1.6 on 2021-05-18 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountsDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=8)),
                ('prefectures', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('producer_name', models.CharField(blank=True, max_length=40)),
                ('producer_type', models.CharField(blank=True, choices=[('1', '野菜'), ('2', '果物'), ('3', '鮮魚'), ('4', '食肉'), ('5', '乳製品'), ('6', '加工食品'), ('7', '飲料'), ('9', 'アルコール飲料'), ('10', '園芸'), ('11', 'その他')], max_length=100)),
                ('certification', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
