# Generated by Django 3.1.6 on 2021-05-18 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountsDetail', '0002_producer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='producer_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
