# Generated by Django 3.1.6 on 2021-05-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsDetail', '0003_producer_producer_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='city',
            new_name='prefectures_city',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='prefectures',
        ),
    ]
