# Generated by Django 3.1.6 on 2021-05-18 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountsDetail', '0004_auto_20210518_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='producer',
            name='producer_img',
            field=models.ImageField(upload_to='producerImg/'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=8)),
                ('prefectures', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('address1', models.CharField(blank=True, max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40)),
                ('restaurant_img', models.ImageField(upload_to='restaurantImg/')),
                ('restaurant_type', models.CharField(blank=True, choices=[('1', '食堂，レストラン'), ('2', '日本料理店'), ('3', '料亭'), ('4', '中華料理店'), ('5', 'ラーメン店'), ('6', '焼肉店'), ('7', 'その他の専門料理店'), ('9', 'そば・うどん店'), ('10', '酒場、ビヤホール'), ('11', 'バー、キャバレー、ナイトクラブ'), ('12', '喫茶店'), ('13', 'その他の飲食店'), ('14', 'ハンバーガー店'), ('15', 'お好み焼・焼きそば・たこ焼店'), ('16', '分類されない飲食店')], max_length=100)),
                ('restaurant_name', models.CharField(blank=True, max_length=40)),
                ('certification', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
